window.debutConfig = {
  name: "Angeline Cereza Andes",
  date: "2025-11-26",
  time: "16:00",
  venue: "Capantaran, Imalnod Legazpi City",
  attire: "Semi-Formal / Formal Attire",
  message: "I am beyond grateful to everyone who made my journey so special. This night is for all of you.",
  hashtag: "Angeline@18",
  rsvpLink: "https://forms.gle/uLp5vNYYRYDzoaPM6",
  music: "assets/music/tenderness.mp3",
  gallery: [
    "assets/images/hero1.jpg",
    "assets/images/hero2.jpg",
    "assets/images/hero3.jpg",
    "assets/images/hero4.jpg",
    "assets/images/hero5.jpg",
    "assets/images/hero6.jpg",
    "assets/images/hero7.jpg",
    "assets/images/hero8.jpg",
    "assets/images/hero9.jpg",
    "assets/images/hero10.jpg",
  ],



  chocolates: [
    "Kasandra Mae Andes",
    "Khloe Mae Andes",
    "Michaela Venice Base",
    "Shannara Marie Llaneta",
    "Sabrina Atole",
    "Quinn Scarlet Lorenzana",
    "Reese Nixie Atuli",
    "Sabrina Lorilla",
    "Mae Berzuela",
    "Reign Golles",
    "Lhian Faye Andes",
    "Nean Cereza",
    "Chrisha Fhate Andes",
    "Gwynn A Lorenzana",
    "Jordyn Rianne Lorenzana",
    "Alliah Mirandilla",
    "Angelica Mae Golles",
    "Trisha Mae Cereza"
  ],

  gifts: [
    "Jenny Maravilla",
    "Justine Maravilla",
    "Darleen Lozada Moriones",
    "Janice Ian Rose Agripa",
    "Donna Jane Abril",
    "Rhea Jasmine Tagob Daet",
    "Judy Ann Lorcha",
    "Siony Cereza",
    "Michelle Lota",
    "Judy Ann Abocado",
    "Wheng Alba",
    "Janice Malasa",
    "Maricris Laguillen",
    "Susan Orolfo",
    "Gina Botiquin",
    "Fatima Cereza",
    "Julie Ann Lota",
    "Leny Rose Rosin"
  ],

  bills: [
    "Bibay Andes",
    "Sharra Nobleza",
    "Sherna Lorenzana",
    "Shiela Mae Atole",
    "Sherryl Andes",
    "Gezell Lorenzana",
    "Janet Lorezana",
    "Beberlyn Llaneta",
    "Charlyn Jackson",
    "Manilyn Abocado",
    "Joezl Kaye Cervantes",
    "Josie Andes",
    "Janice Malasa",
    "Roselyn Lladones",
    "Jenny Lorenzana",
    "Richard Abocado",
    "Michael Ibarbia",
    "Rodel Lorenzana"
  ],

  shots: [
    "Rey Alamo",
    "John Carlo Lleva",
    "Kent Daniel Argote",
    "Kervin Ariola",
    "Harry Postrado",
    "Jonh Rovic Dioneda",
    "Francis Sapıter",
    "Henry Agripa",
    "Kyle Matthew Acebedo",
    "Jonh Cedrick Abrigo",
    "Carlos Richard Geal Dienzo",
    "Aljohn Benetiz",
    "Jonel Andes",
    "Jonh Michael Manalo",
    "Alex Bonso",
    "Renz Atuli",
    "Lance Aldrin Valladolid",
    "Jay Ar Antones"
  ],

  roses: [
    "Mark Lester Andes",
    "Carl Jhon Andes",
    "Jerick Cereza",
    "Joshua Cereza",
    "Ranito Alfred Andes",
    "Rhandy Jae Llaneta",
    "Christopher Alegre",
    "Ken Solancho",
    "Acxell Cuna",
    "Jhon Mark Maravilla",
    "Jaycon Agripa",
    "Rashid Binalingbing",
    "Prince Darly Lorilla",
    "Mark Owen Trilles",
    "Jeremy Peralta",
    "Jhon Benedict Andes",
    "Gabriel Andes",
    "Marlon Andes"
  ],

  treasures: [
    "Margareth Atole",
    "Samantha Andes",
    "Julia Kristine Guiriba",
    "Atasha Coleen Padilla",
    "Aisie Ardales",
    "Eloiza Callos",
    "Jovy Gonzales",
    "Erica Pontuya",
    "Camille Lorilla",
    "Riana Atuli",
    "Antonette Atuli",
    "Kathlen Abrigo",
    "Czarelle Buena",
    "Angilyn Maravilla",
    "Antonette Andes",
    "Janell Andes",
    "Kristine Ann",
    "Kent Llaneta"
  ],

  candles: [
    "Mae Ann Sanpablo",
    "Sheena Mae Aranil",
    "Jenny Lopez",
    "Monica Abrigo",
    "Bernadette Mendenilla",
    "Angel Arispe",
    "Jasmine Lorilla",
    "Jasmime Jayla Desuyo",
    "Ashley Orolfo",
    "Angela Montenegro",
    "Kristan Jela Ignacio",
    "Cindy Candia",
    "Alliah Grate",
    "Wenna Balsarza",
    "Ma. Laiysa Asejo",
    "Dianne Ariate",
    "Yishin Nogales",
    "Ashley Jane Agripa"
  ],

  bears: [
    "Akkio Fort Nobleza",
    "Hao Loveriza",
    "John Austin Mayores",
    "Daellan John Gentilizo",
    "Jonh Christoper Andes",
    "Alexis Austin Ibarbia",
    "Kenzo Asaytuno",
    "Nikko Arizapa",
    "Laurence Lota",
    "Matthew Lorcha",
    "Maxwill Kurt Molano",
    "Nash Manaog",
    "Luke Golles",
    "Nikko Daen",
    "Mac Daniel Ibarbia",
    "Jayke Cereza",
    "Harry Opemia",
    "Aeron Abadesa"
  ]

};



